config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  authenticate :user do
    resources  :lists
    resources  :tasks, type: 'Task'
    resources  :subtasks, controller: 'tasks', type: 'Subtask'
    resources  :favorites

    match 'add-favorite/:list_id', to: 'favorites#add_favorite_list', via: :get
    get 'list_stream' => 'lists#notification'
    
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many   :tasks, dependent: :destroy
  has_many   :favorites, dependent: :destroy
  accepts_nested_attributes_for :tasks, allow_destroy: true

  validates :name, presence: true

  scope :last_updated, -> {
    order('updated_at DESC, created_at DESC').limit(1)
  }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  validates :name,        presence: true
  validates :description, presence: true

  def self.types
    %w(Subtask)
  end
end

app/models/tasks/subtask.rb
class Subtask < Task
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favorites, through: :lists, dependent: :destroy
  has_many :lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  after_filter { flash.discard if request.xhr? }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorities = Favorite.where(user_id: current_user.id)
  end

  def add_favorite_list
    @favorite = Favorite.where(list_id: params[:list_id], user_id: current_user.id)
    
    if @favorite.present?
      respond_to do |format|
        format.js { flash[:notice] = 'List has already been favorited.' }
      end
    else
      @favorite = Favorite.new(list_id: params[:list_id], user_id: current_user.id)

      respond_to do |format|
        if @favorite.save
          format.js { flash[:notice] = 'List was successfully favorited.' }
        end
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:favorite).permit(:list_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  
  include ActionController::Live

  def notification
    # SSE expects the `text/event-stream` content type
    response.headers['Content-Type'] = 'text/event-stream'

    sse = SSE.new(response.stream)

    last_updated = List.last_updated.first
    if recently_changed? last_updated
      begin
        sse.write(last_updated.to_json, event: 'results')
        sleep 1
      rescue IOError
        # When the client disconnects, we'll get an IOError on write
      ensure
        sse.close
      end
    end
    render nothing: true
  end

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
    @list.tasks.build
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = current_user.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.js { flash[:notice]='List was successfully created.' }
      else
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.js { flash[:notice]='List was successfully updated.'}
      else
        format.js { render :edit }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
    end
  end

  private
    def recently_changed? last_list
      last_list.created_at > 5.seconds.ago or
        last_list.updated_at > 5.seconds.ago
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :status, :user_id, 
        tasks_attributes:[:id, :name, :description, :_destroy, :type])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_type
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = type_class.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = type_class.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = type_class.new(task_params)
    @father_task = Task.where(id: @task.index_task)
    @task.list_id = @father_task.first.list_id

    respond_to do |format|
      if @task.save
        format.js { flash[:notice]='Task was successfully created.' }
      else
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /tasks/1
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.js { flash[:notice]='Task was successfully updated.'}
      else
        format.js { render :edit }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = type_class.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(type.underscore.to_sym).permit(:name, :description, :list_id, :type, :index_task)
    end

    def set_type
      @type = type
    end
 
    def type 
      Task.types.include?(params[:type]) ? params[:type] : "Task"
    end
 
    def type_class 
      type.constantize 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
  def link_to_function(name, *args, &block)
     html_options = args.extract_options!.symbolize_keys

     function = block_given? ? update_page(&block) : args[0] || ''
     onclick = "#{"#{html_options[:onclick]}; " if html_options[:onclick]}#{function}; return false;"
     href = html_options[:href] || '#'

     content_tag(:a, name, html_options.merge(:href => href, :onclick => onclick))
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def sti_task_path(type = "task", task = nil, action = nil)
    send "#{format_sti(action, type, task)}_path", task
  end
   
  def format_sti(action, type, task)
    action || task ? "#{format_action(action)}#{type.underscore}" : "#{type.underscore.pluralize}"
  end
   
  def format_action(action)
    action ? "#{action}_" : ""
  end
end

app/views/favorites/add_favorite_list.js.erb
$("#notice").html("<%= flash[:notice] %>").removeClass("hide");

app/views/favorites/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">My Favorite Lists</div>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Status</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @favorities.each do |favorite| %>
        <tr>
          <td><%= favorite.list.name %></td>
          <td><%= (favorite.list.status) ? 'Private' : 'Public' %></td>
          <td>
            <%= link_to list_path(favorite.list.id) do %>
              <span class="glyphicon glyphicon-eye-open"></span>
            <% end%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  </div>
</div>

app/views/home/index.html.erb
<h1>Welcome</h1>
<div class="jumbotron">
  <h1>Hello, world!</h1>
  <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters</p>
  <p>
  <a class="btn btn-primary inverse btn-lg" href="#" role="button">Learn more</a></p>
</div>

<div class="row">
  
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">What's up?</h3>
      </div>
      <div class="panel-body">
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">What's up?</h3>
      </div>
      <div class="panel-body">
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">What's up?</h3>
      </div>
      <div class="panel-body">
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Autoseg</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: "menu/navbar"%>
  <div class="container">
    <% if notice %><div class="alert alert-info"><%= notice %></div><% end %>
    <% if alert %><div class="alert alert-warning"><%= alert %></div><% end %>
    
    <div class="alert alert-warning hide">
      <ul id="lists"></ul>
    </div>
    
    <%= yield %>

    <div class="dialog"></div>
  </div>

</body>
<script type="text/javascript">

</script>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list, html: {class:'form-horizontal task_form'}, remote: :true) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h6><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h6>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-11">
      <h4>List</h4>
      <div class="form-group">
        <%= f.hidden_field :user_id, value: current_user.id %>
        <label class="col-xs-3 control-label">Name</label>
        <div class="col-xs-9">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-10">
          <%= f.check_box :status %> Private
        </div>
      </div>

      <hr>
      
      <h4>Task</h4>
      <%= f.fields_for :tasks  do |builder| %>
        <%= render 'task_fields', :f => builder %>
      <% end %>
      
      <div class="form-group">
        <div class="col-sm-4">
          <%= link_to_add_fields "Add task", f, :tasks %>
        </div>
      </div>
      
      <div class="actions">
        <div class="col-sm-offset-3 col-sm-10">
          <%= f.submit "Create", class: 'btn btn-default' %>
        </div>
      </div>
    </div>
  </div>
<% end %>


<script type="text/javascript">
  
function remove_fields(link) {
  $(link).prev("input[type=hidden]").val("1");
  $(link).closest(".fields").hide();
}

function add_fields(link, association, content) {
  var new_id = new Date().getTime();
  var regexp = new RegExp("new_" + association, "g")
  $(link).parent().before(content.replace(regexp, new_id));
}
</script>

app/views/lists/_task_fields.html.erb
<div class="fields">
  <div class="form-group">
    <label class="col-xs-3 control-label">Name</label>
    <div class="col-xs-9">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-xs-3 control-label">Description</label>
    <div class="col-xs-9">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="col-sm-offset-3 col-sm-10">
      <%= f.hidden_field :_destroy %>
      <%= f.hidden_field :type, value: 'Task' %>
      <%= link_to_remove_fields "remove", f %>
    </div>
  </div>
</div>

app/views/lists/create.js.erb
$('.dialog').dialog( "close" );
$('#notice').html("<%= flash[:notice] %>").removeClass('hide');

app/views/lists/edit.js.erb
$('.dialog').html('<%= j(render :partial => "lists/edit")%>')
            .dialog({
              maxHeight: 550,
              modal: true,
              resizable: false,
              title: "Edit List",
              width: 600
            });

app/views/lists/index.html.erb
<div id="notice" class="alert alert-info hide"></div>
<div class="row">
  <div class="col-md-10">
    <%= link_to 'New List', new_list_path, class: 'btn btn-default', remote: :true %>
  </div>
</div>
<br>

<div class="panel panel-default">
  <div class="panel-heading">Lists</div>
    <ul class="list-group">
      
      <li class="list-group-item list-group-item-info">
        <div class="row">
          <div class="col-md-4">Name</div>
          <div class="col-md-2">Status</div>
          <div class="col-md-1">Favorite</div>
          <div class="col-md-3">User</div>
          <div class="col-md-2">Actions</div>
        </div>
      </li>
      <% @lists.each do |list| %>
        <% if (list.user_id == current_user.id) || (list.status == false) %>
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-4"><%= list.name%></div>
              <div class="col-md-2"><%= (list.status) ? 'Private' : 'Public' %></div>
              <div class="col-md-1">
                <%= link_to  "/add-favorite/#{list.id}", id: 'add-fav', remote: true do %> 
                  <span class="glyphicon glyphicon-star-empty"></span>
                <% end %>
              </div>
              <div class="col-md-3"><%= list.user.email %></div>
              <div class="col-md-2">
                <div class="row">
                  <div class="col-md-4">
                    <%= link_to list do %>
                      <span class="glyphicon glyphicon-eye-open"></span>
                    <% end %>
                  </div>
                  <% if list.user_id == current_user.id %>
                    <div class="col-md-4">
                      <%= link_to edit_list_path(list), remote: :true do %>
                        <span class="glyphicon glyphicon-edit"></span>
                      <% end%>
                    </div>
                    <div class="col-md-4">
                      <%= link_to  list, method: :delete, data: { confirm: 'Are you sure?' } do %>
                        <span class="glyphicon glyphicon-remove-circle"></span>
                      <% end%>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
            <ul class="list-group">
              <li class="list-group-item list-group-item-info">
                <div class="row">
                  <div class="col-md-6">Name</div>
                  <div class="col-md-6">Description</div>
                </div>
              </li>
              <% list.tasks.where(type: 'Task').each do |task|%>
                <li class="list-group-item">
                  <div class="row">
                    <div class="col-md-6"><%= task.name %></div>
                    <div class="col-md-6"><%= task.description %></div>
                  </div>

                  <ul class="list-group">
                    <% list.tasks.where(type: 'Subtask').each do |subtask|%>
                      <% if task.id == subtask.index_task %>
                        <li class="list-group-item">
                          <div class="row">
                            <div class="col-md-6"><%= subtask.name %></div>
                            <div class="col-md-6"><%= subtask.description %></div>
                          </div>
                        </li>
                      <% end %>
                    <% end %>
                  </ul>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/lists/new.js.erb
$('.dialog').html('<%= j(render :partial => "lists/new")%>')
            .dialog({
              maxHeight: 550,
              modal: true,
              resizable: false,
              title: "New List",
              width: 600
            });

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">List</div>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @list.name %></td>
        <td><%= (@list.status) ? 'Private' : 'Public' %></td>
      </tr>
    </tbody>
  </table>
</div>


<% if @list.user_id == current_user.id %>
  <%= link_to 'Edit', edit_list_path(@list), remote: :true %> |
<% end %>
<%= link_to 'Back', lists_path %>

app/views/menu/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#" onclick="Turbolinks.visit('<%= lists_path %>')">List 
        <li><a href="#" onclick="Turbolinks.visit('<%= subtasks_path %>')">SubTasks</a></li>
        <li><a href="#" onclick="Turbolinks.visit('<%= favorites_path %>')">Favorites</a></li>>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tasks/_edit.html.erb
<%= render 'form' %>

app/views/tasks/_form.html.erb
<%= form_for(@task, html: {class:'form-horizontal task_form'}, remote: true) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h4>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-11">
    <div class="form-group">
      <label class="col-xs-3 control-label">Task</label>
      <div class="col-xs-5">
        <%= f.select :index_task, options_from_collection_for_select(Task.where(type: "Task"), "id", "name", @task.index_task), include_blank: true %>
      </div>

    </div>

    <div class="form-group">
      <label class="col-xs-3 control-label">Name</label>
      <div class="col-xs-5">
        <%= f.text_field :name, class: 'form-control'  %>
      </div>
    </div>

    <div class="form-group last">
      <label class="col-xs-3 control-label">Description</label>
      <div class="col-xs-5">
        <%= f.text_area :description, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-10">
        <%= f.submit "Create", class: 'btn btn-default' %>
      </div>
    </div>
  </div>
</div>
<% end %>


<script type="text/javascript">
  <%= render template: 'tasks/task_utils.js' %>
</script>

app/views/tasks/_new.html.erb
<%= render 'form' %>

app/views/tasks/create.js.erb
$('.dialog').dialog( "close" );
$('#notice').html("<%= flash[:notice] %>").removeClass('hide');

app/views/tasks/edit.js.erb
$('.dialog').html('<%= j(render :partial => "tasks/edit")%>')
            .dialog({
              maxHeight: 550,
              modal: true,
              resizable: false,
              title: "Edit Task",
              width: 600
            });

app/views/tasks/index.html.erb
<div id="notice" class="alert alert-info hide"></div>
<div class="row">
  <div class="col-md-10">
    <%= link_to 'New', sti_task_path(@type, nil, :new), class: 'btn btn-default', remote: :true %>
  </div>
</div>
<br>

<div class="panel panel-default">
  <div class="panel-heading">Tasks</div>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>List</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <% if task.list.user.id == current_user.id %>
        <tr>
          <td><%= task.name %></td>
          <td><%= task.description %></td>
          <td><%= task.list.name %></td>
          <td>
            <%= link_to task do %>
              <span class="glyphicon glyphicon-eye-open"></span>
            <% end %>
          </td>
          <td>
            <%= link_to sti_task_path(task.type, task, :edit), remote: :true do %>
              <span class="glyphicon glyphicon-edit"></span>
            <% end%>
          </td>
          <td><%= link_to  sti_task_path(task.type, task), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-remove-circle"></span>
            <% end%>
          </td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/new.js.erb
$('.dialog').html('<%= j(render :partial => "tasks/new")%>')
            .dialog({
              maxHeight: 550,
              modal: true,
              resizable: false,
              title: "New Task",
              width: 600
            });

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">Task</div>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>List</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @task.name %></td>
        <td><%= @task.description %></td>
        <td><%= @task.list.name %></td>
      </tr>
    </tbody>
  </table>
</div>

<%= link_to 'Edit', edit_task_path(@task), remote: :true if @task.list.user_id == current_user.id %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/task_utils.js.erb
$(document).ready(function() {
  $('#new_task')  
    // Add button click handler
    .on('click', '.addButton', function() {
        var $template = $('#add-fields'),
            $clone    = $template
                            .clone()
                            .removeClass('hide')
                            .removeAttr('id')
                            .insertAfter($(".last"))
    })

    // Remove button click handler
    .on('click', '.removeButton', function() {
        var $row    = $(this).parents('.append')

        // Remove element containing the option
        $row.remove();
    })
});

app/views/tasks/update.js.erb
$('.dialog').dialog( "close" );
$('#notice').html("<%= flash[:notice] %>").removeClass('hide');